language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - i.casi@alumnos.upm.es
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=iraticasi-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR
